### ISSUE TITLE
Tags page

### ISSUE THREAD

**Issue by hwchen** [aos/temple#10]
Hello,

From what I can see, each tag has its own page, but there is not a way to see all tags on one page. Am I mistaken? I'm hoping to have a link to a tags page in the top menu. Thanks!

**Comment by irmanfrdev** [comment]
Just add /tags/ in your base URL. example: <BASE_URL>/tags/
But if you want to add it to top menu, you have to override the theme

**Comment by hwchen** [comment]
Thanks!
