### ISSUE TITLE
Customize Date Format

### ISSUE THREAD

**Issue by ilikeorangutans** [aos/temple#12]
Love the theme and would really appreciate a way of customizing the date format. Right now it's hard coded to `day-month-year`. Could you turn this into a configuration parameter?

**Comment by instantkaffee** [comment]
Adjust all entries to:
`<time datetime="{{ $page.Date.Format "2006-01-02" }}">`

**Comment by aos** [comment]
That's a great idea. I'm a little busy currently but will get to it in the next week or so. If anyone wants to submit a PR for this, I'd be more than happy to look it over
