### ISSUE TITLE
Support toc

### ISSUE THREAD

**Issue by zbing3** [aos/temple#21]
Support toc？

**Comment by aos** [comment]
Hey @zbing3 Do you mean a table of contents?

**Comment by Dieken** [comment]
@aos  I guess @zbing3 does mean table of contents.

I made a local  rude change,  it's better to have a variable to control it, or even better to use a partial template.

```diff
diff --git a/layouts/_default/single.html b/layouts/_default/single.html
index 75a1d9a..6d1d44e 100644
--- a/layouts/_default/single.html
+++ b/layouts/_default/single.html
@@ -35,6 +35,7 @@
       </div>
 
       <div class="post-content">
+        {{ .TableOfContents }}
         {{ .Content }}
       </div>
     </div>
```

**Comment by aos** [comment]
@Dieken Ahh that makes sense. I would work on this but I'm very busy and it will be a few weeks before I can get started. I'm happy to review any PRs for it though

**Comment by Dieken** [comment]
@aos  @zbing3   please have a look at PR #28,  thanks!
